### ISSUE TITLE
Missing property types

### ISSUE THREAD

**Issue by AdaShoelace** [notgull/breadx#36]
PropertyTypes such as `Cardina`l and `Window` is missing from the enum `PropertyType`.
Is there an plan regarding the implementation for this or may I try to implement it?
From reading `xml/xproto.xml` my understanding is that it just needs to be added to the `PropertyType` enum?
Is this interpretation correct?

**Comment by notgull** [comment]
No, I just forgot about it. If you could implement that, that would be great.
