### ISSUE TITLE
Virtual desktops management

### ISSUE THREAD

**Issue by ngirard** [notgull/breadx#9]
I wish to be able to create/destroy/rename virtual desktops, and move windows between them.
Are you planning address this in Breadx ?

Cheers, and thanks for your work !

**Comment by not-a-seagull** [comment]
Thanks for filing this issue!

I'm relatively sure virtual desktops are largely a window manager-centric thing, rather than an implementation of X11. For me, at least, I'm able to move my windows between virtual desktops. Would you mind clarifying?

**Comment by not-a-seagull** [comment]
Looking at this again without sleepy eyes, it seems clearer that you want to be able to manipulate virtual desktops from breadx. Does X usually offer this functionality? If I recall correctly, it does not.

**Comment by zuoxinyu** [comment]
Virtual desktop is just a special container holds a group of windows. It's not a primary conception in X proto.

**Comment by notgull** [comment]
Thank you for the clarification. Closing this issue.
